# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef4b1cd072f222592c295275a4f4b27136fc2c12bdf96f60878512e76c626787d54f3bbaea47355de89d5662546cd42b5bd36bb650e237e594fd491a4769cb4e

test:
  secret_key_base: 275e32a014d19af7c6ff33e434d2825bcce3cbe91f15079750d85d56fbe927ef55d83db6e5f982ae0cb8b8201659b12d9b7f0f53d9712a752e1688978c454a7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
